### ISSUE TITLE
Discord Link in readme invalid

### ISSUE THREAD

**Issue by TrangPham** [medplum/foomedical#81]
![Screen Shot 2023-02-10 at 12 22 16 PM](https://user-images.githubusercontent.com/2117313/218190239-579b2ab5-1a86-48a4-a89c-b1118a2cd185.png)

I tried joining the discord by clicking the link within readme and it showed me this

**Comment by reshmakh** [comment]
@TrangPham - does this one work for you? https://discord.gg/UBAWwvrVeN

**Comment by TrangPham** [comment]
Sorry I forgot to reply but it does :)
